databases:
  - name: 設定したデータベース名
    databaseName: 設定したデータベース名（Info内のConnectionsにあるDatabaseの値）
    user: 設定したユーザ名
    region: Oregon

services:
  - type: web
    name: 設定したデータベース名
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 設定したデータベース名
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
