databases:
  - name: KansaiTraveler
    databaseName: kansaitraveler_production
    user: kansai_user
    region: Oregon

services:
  - type: web
    name: KansaiTraveler
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: KansaiTraveler
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
